In [1]:
import torch

In [2]:
x = [ 2, 9, 5, 16, 23, 35]

In [3]:
#检查是否为tensor对象
torch.is_tensor(x)

False

In [5]:
y = torch.rand(1,2)
y

tensor([[0.7914, 0.8993]])

In [6]:
torch.is_tensor(y)

True

In [7]:
torch.numel(y) #统计tensor中的元素个数

2

In [10]:
#创建全0的tensor
z = torch.zeros(3,3)

In [11]:
torch.numel(z)

9

In [12]:
#创建对角线为1的tensor
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
#将numpy转化为tensor
import numpy as np

x = np.array([ 3, 4, 5, 6, 7])
x

array([3, 4, 5, 6, 7])

In [14]:
torch.from_numpy(x)

tensor([3, 4, 5, 6, 7], dtype=torch.int32)

In [15]:
#切分 linspace
torch.linspace( 2, 10, steps=5)

tensor([ 2.,  4.,  6.,  8., 10.])

In [16]:
torch.linspace( 2, 10, steps=10) #steps 表示切分成几份

tensor([ 2.0000,  2.8889,  3.7778,  4.6667,  5.5556,  6.4444,  7.3333,  8.2222,
         9.1111, 10.0000])

In [17]:
#创建均匀的分布，值在0-1之间
torch.rand(10)

tensor([0.8733, 0.8644, 0.9699, 0.6772, 0.2871, 0.9315, 0.3337, 0.2239, 0.7818,
        0.6542])

In [19]:
#正态分布，均值为0，方差为1
torch.randn(10)

tensor([ 2.4344, -1.7181, -0.2946,  0.1902,  0.8805,  0.2268, -0.4094,  1.6254,
        -1.7792, -0.9363])

In [20]:
#选择随机数
torch.randperm(10)

tensor([6, 4, 2, 0, 3, 7, 8, 5, 9, 1])

In [21]:
#生成一个区间的数 
torch.arange( 10 ,30, 5) #前两个范围，最后是步长，是个开区间

tensor([10, 15, 20, 25])

In [22]:
#获取行或列的最大最小值
x = torch.randint( 1, 99,(3,3))
x

tensor([[41, 12, 39],
        [10, 54, 94],
        [11, 50, 50]])

In [23]:
torch.argmin(x, dim=0) #每一列最小值的位置

tensor([1, 0, 0])

In [24]:
torch.argmax(x, dim=0)

tensor([0, 1, 1])

In [26]:
#连接
x = torch.randint(1,10,(2,3))
x

tensor([[3, 2, 3],
        [2, 9, 3]])

In [27]:
torch.cat((x,x))

tensor([[3, 2, 3],
        [2, 9, 3],
        [3, 2, 3],
        [2, 9, 3]])

In [28]:
torch.cat((x,x), dim=1) #1s是横轴，默认是0

tensor([[3, 2, 3, 3, 2, 3],
        [2, 9, 3, 2, 9, 3]])

In [29]:
# chunk 切块
a = torch.randint(1,10,(3,3))
a

tensor([[7, 8, 7],
        [9, 4, 2],
        [9, 7, 8]])

In [34]:
'''
torch.chunk(input, chunks, dim=0) → List of Tensors
Splits a tensor into a specific number of chunks. Each chunk is a view of the input tensor.

Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by chunks.

Parameters
input (Tensor) – the tensor to split

chunks (int) – number of chunks to return

dim (int) – dimension along which to split the tensor
'''
torch.chunk(a,2,0) 

(tensor([[7, 8, 7],
         [9, 4, 2]]),
 tensor([[9, 7, 8]]))

In [35]:
torch.chunk(a,3,1)

(tensor([[7],
         [9],
         [9]]),
 tensor([[8],
         [4],
         [7]]),
 tensor([[7],
         [2],
         [8]]))

In [37]:
# 根据索引选择
x = torch.randn(4,4)
x

tensor([[ 0.4864,  0.7988,  1.5037,  0.7101],
        [ 0.5547, -0.1214,  1.6272,  0.6033],
        [ 0.6982,  2.4126, -0.5919,  0.6042],
        [-0.0585,  0.4432, -1.3733, -0.3579]])

In [38]:
indices = torch.tensor([0,2])

In [39]:
torch.index_select(x,0,indices)

tensor([[ 0.4864,  0.7988,  1.5037,  0.7101],
        [ 0.6982,  2.4126, -0.5919,  0.6042]])

In [40]:
#分割
x = torch.tensor([1,2,3,4,5,6,7])
x

tensor([1, 2, 3, 4, 5, 6, 7])

In [42]:
torch.split(x,3)

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7]))

In [45]:
#转置
x = torch.tensor([[1,2],[3,4]])
x

tensor([[1, 2],
        [3, 4]])

In [46]:
x.t()

tensor([[1, 3],
        [2, 4]])

In [48]:
x.transpose(1,0)

tensor([[1, 3],
        [2, 4]])

In [49]:
# 运算
x = torch.tensor([[1,2],[3,4]])
x

tensor([[1, 2],
        [3, 4]])

In [50]:
torch.add(x,1)

tensor([[2, 3],
        [4, 5]])

In [51]:
torch.mul(x,2)

tensor([[2, 4],
        [6, 8]])

In [52]:
#索引获取
x = torch.rand(2,3)
x

tensor([[0.9665, 0.9646, 0.0204],
        [0.4142, 0.6003, 0.1426]])

In [55]:
torch.take(x,torch.tensor([0,2,5]))

tensor([0.9665, 0.0204, 0.1426])

In [57]:
#缩小,返回一个更窄的张量
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
'''
torch.narrow(input, dim, start, length) 
nput (Tensor) – the tensor to narrow
dim (int) – the dimension along which to narrow
start (int) – the starting dimension
length (int) – the distance to the ending dimension
'''
torch.narrow(x,0,0,2)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [59]:
torch.narrow(x,1,1,2)

tensor([[2, 3],
        [5, 6],
        [8, 9]])