In [1]:
import torch
import pandas as pd
import numpy as np

In [2]:
#mean
a = torch.tensor([3,4,5,6],dtype=torch.float)
torch.mean(a)

tensor(4.5000)

In [3]:
#sum
torch.sum(a)

tensor(18.)

In [4]:
#计算所有元素的积
torch.prod(a)

tensor(360.)

In [5]:
#max
torch.max(a)

tensor(6.)

In [6]:
#min
torch.min(a)

tensor(3.)

In [7]:
#最大最小值下标
torch.argmax(a)

tensor(3)

In [8]:
torch.argmin(a)

tensor(0)

In [9]:
#标准差
torch.std(a)

tensor(1.2910)

In [10]:
#方差
torch.var(a)

tensor(1.6667)

In [11]:
#中位数
torch.median(a)

tensor(4.)

In [12]:
#众数
torch.mode(a)

torch.return_types.mode(
values=tensor(3.),
indices=tensor(0))

In [13]:
#直方图
torch.histc(a)

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [14]:
#定义随机种子
torch.manual_seed(222)

In [15]:
#组合。拼接
a1 = torch.tensor([1,2,3],dtype=torch.float)
a2 = torch.tensor([4,5,6],dtype=torch.float)

torch.cat([a1,a2],dim=0) #横向

tensor([1., 2., 3., 4., 5., 6.])

In [16]:
torch.stack([a1,a2],dim=0) #纵向

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
#按照条件从x，y中选出满足条件的元素
x = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
y = torch.tensor([11,22,33,44,55,66])
torch.where(x>6) #输出对应的索引值 

(tensor([2, 2, 2]), tensor([0, 1, 2]))

In [18]:
#在指定维度上按照索引值输出tensor
b = torch.Tensor([[1,2,3],[4,5,6]])
index_1 = torch.LongTensor([[0,1],[2,0]])
index_2 = torch.LongTensor([[0,1,1],[0,0,0]])

print(torch.gather(b,dim=1,index=index_1)) 
print(torch.gather(b,dim=1,index=index_2)) 

tensor([[1., 2.],
        [6., 4.]])
tensor([[1., 2., 2.],
        [4., 4., 4.]])


In [19]:
#按照指定索引输出tensor
a = torch.linspace(1,12,steps=12).view(3,4)
print(a)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [20]:
b = torch.index_select(a,0,torch.tensor([0,2]))
print(b)


tensor([[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]])


In [21]:
c = torch.index_select(a,1,torch.tensor([0,2]))
print(c)

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])


In [22]:
#Tensor与tensor的区别
a = torch.Tensor([1,2]) #用的是类，默认float
print(a)
print(a.type())
b = torch.tensor([3,4]) #用的函数,默认int类型
print(b)
print(b.type())
#大写的Tensor必须要输入向量，不能是标量

tensor([1., 2.])
torch.FloatTensor
tensor([3, 4])
torch.LongTensor


In [23]:
#按照mask输出tensor，输出为向量

x = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
mask = x.ge(5) #x>5 的为True
mask

tensor([[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]])

In [24]:
torch.masked_select(x,mask)

tensor([5, 6, 7, 8, 9])

In [25]:
#将输入看成ID-tensor，按照索引得到输出tensor
src = torch.tensor([[4,3,5],
                  [6,7,8]])
torch.take(src,torch.tensor([0,2,5]))

tensor([4, 5, 8])

In [26]:
#按照某个维度平均分块
a = torch.Tensor([[1,2,3]])
b = torch.Tensor([[4,5,6],
                 [7,8,9],
                 [10,11,12]])
c = torch.cat([a,b],dim=0)
print(c)
d = torch.chunk(c,4,dim=0)
print(d)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.]]), tensor([[7., 8., 9.]]), tensor([[10., 11., 12.]]))


In [27]:
#按照某个维度依照第二个参数给出的list或者int进行分割tensor
#第二个参数有两种形式
#一种分割份数，和chunk差不多
#第二种是分割方案，是一个list，待分割张量将会分割为len(list)份，每一份大小取决于list中的元素
e = torch.split(c,2,dim=0)
print(e)
f = torch.split(c,[1,2,1],dim=0)
print(f)

(tensor([[1., 2., 3.],
        [4., 5., 6.]]), tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]]))
(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.],
        [7., 8., 9.]]), tensor([[10., 11., 12.]]))


In [28]:
#reshape
a = torch.tensor([[1,2,3],
                 [4,5,6]])
b = torch.reshape(a,(3,2))
print(b)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [29]:
#只针对2d的转置
a = torch.tensor([[1,2,3],
                 [4,5,6]])
b = torch.t(a)
print(b)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [30]:
#交换两个维度 transpose(input,dim0,dim1)
a = torch.tensor([[1,2,3],
                 [4,5,6]])
torch.transpose(a,1,0)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [31]:
#对数据维度进行压缩，去掉维数为1的维度
a = torch.tensor([[1],[1]])
torch.squeeze(a)

tensor([1, 1])

In [32]:
#对数据维度进行扩充。给指定位置加上维数为1的维度
a = torch.tensor([1,2,3,4])
torch.unsqueeze(a,1)

tensor([[1],
        [2],
        [3],
        [4]])

In [33]:
#去除某个维度
a = torch.tensor([[1,2,3],
                 [4,5,6]])
print(torch.unbind(a,dim=0))

(tensor([1, 2, 3]), tensor([4, 5, 6]))


In [34]:
#按照给定维度翻转张量
a = torch.tensor([[1,2,3],
                 [4,5,6]])

torch.flip(a,[0,1])

tensor([[6, 5, 4],
        [3, 2, 1]])

In [35]:
#按照指定的维度和旋转次数进行张量旋转
a = torch.tensor([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
torch.rot90(a,1,[0,1]) #横轴纵轴都进行了一次翻转

tensor([[3, 6, 9],
        [2, 5, 8],
        [1, 4, 7]])