In [1]:
import torch
import numpy as np

# 构建

In [2]:
#标量
a = torch.tensor(4.0)
print("标量：",a)

标量： tensor(4.)


In [3]:
#向量
b = torch.tensor([1.5,0,3])
print("向量：",b)

向量： tensor([1.5000, 0.0000, 3.0000])


In [4]:
#矩阵
c = torch.tensor([[1,2],[3,4]])
print("矩阵：",c)

矩阵： tensor([[1, 2],
        [3, 4]])


In [5]:
#多维矩阵
d = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print("多维矩阵：",d)

多维矩阵： tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [6]:
#创建空的tensor
e = torch.empty(5,3)
print(e)

tensor([[9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39],
        [8.4490e-39, 1.0653e-38, 9.9184e-39],
        [8.4490e-39, 8.9082e-39, 8.9082e-39]])


In [7]:
#创建随机矩阵
f = torch.rand(5,3)

print(f)

tensor([[0.7992, 0.8437, 0.3167],
        [0.1142, 0.1135, 0.0816],
        [0.0669, 0.1073, 0.2714],
        [0.3257, 0.9865, 0.2308],
        [0.4817, 0.2304, 0.7445]])


In [8]:
#创建一个全0的矩阵,数据类型为long
g = torch.zeros(5,3,dtype=torch.long) 
print(g)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
#创建全1的矩阵
h = torch.ones(5,3)
print(h)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [10]:
#创建一个产生随机元素的矩阵，其shape与另一个矩阵的shape大小一致
i = torch.rand_like(h,dtype=torch.float)
print(i)

tensor([[0.4704, 0.5700, 0.0417],
        [0.2691, 0.9765, 0.6854],
        [0.4202, 0.9677, 0.0883],
        [0.7737, 0.7483, 0.4741],
        [0.3202, 0.7780, 0.6259]])


# 基本预算

In [11]:
#加法
j = torch.tensor([1,2,3])
k = torch.tensor([4,5,6])

print("Tensor 加法",j+k)
print("Tensor 加法",torch.add(j,k))
#改变原始的j
print("Tensor 加法",j.add_(k))
print(j)
print(k)

Tensor 加法 tensor([5, 7, 9])
Tensor 加法 tensor([5, 7, 9])
Tensor 加法 tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([4, 5, 6])


In [12]:
#除法
l = torch.tensor([6,12])
m = torch.tensor([3,6])

print("Tensor 除法",1//m)
print("Tensor 除法",torch.true_divide(1,m))

Tensor 除法 tensor([0, 0])
Tensor 除法 tensor([0.3333, 0.1667])


C:\Users\user\anaconda3\lib\site-packages\torch\_tensor.py:579: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ..\aten\src\ATen\native\BinaryOps.cpp:467.)
  return torch.floor_divide(other, self)


In [13]:
#二维矩阵的乘法
n = torch.ones(1,2)
p = torch.ones(2,1)
print("Tensor 乘法",torch.mm(n,p))
print("Tensor 乘法",torch.matmul(n,p))
print("Tensor 乘法",n@p)
#替代
print("Tensor 乘法",n.mm(p))

Tensor 乘法 tensor([[2.]])
Tensor 乘法 tensor([[2.]])
Tensor 乘法 tensor([[2.]])
Tensor 乘法 tensor([[2.]])


In [14]:
#幂运算
q = torch.tensor([2,3])
print("Tensor 幂运算",torch.pow(q,2))
print("Tensor 幂运算",q.pow(2))
print("Tensor 幂运算",q**2)

Tensor 幂运算 tensor([4, 9])
Tensor 幂运算 tensor([4, 9])
Tensor 幂运算 tensor([4, 9])


In [15]:
#根号
r = torch.tensor([4,16],dtype=torch.float)
print("Tensor 开方", r.sqrt())
print("Tensor 开方", torch.sqrt(r))

Tensor 开方 tensor([2., 4.])
Tensor 开方 tensor([2., 4.])


In [16]:
#对数运算
s1 = torch.tensor([8,16,32],dtype=torch.float)
print("Tensor 对数运算",torch.log2(s1))
s2 = torch.tensor([100,1000,10000],dtype=torch.float)
print("Tensor 对数运算",torch.log10(s2))
s3 = torch.tensor([20,30,40],dtype=torch.float)
print("Tensor 对数运算",torch.log(s3))#默认以e为底

Tensor 对数运算 tensor([3., 4., 5.])
Tensor 对数运算 tensor([2., 3., 4.])
Tensor 对数运算 tensor([2.9957, 3.4012, 3.6889])


In [17]:
#取整，取余
t = torch.tensor([3.5,9.982,4.215])
print("向下取整",t.floor())
print("向上取整",t.ceil())
print("四舍五入",t.round())
print("只取整数部分",t.trunc())
print("只取小数部分",t.frac())
print("取余数",torch.tensor([25,31])%7)

向下取整 tensor([3., 9., 4.])
向上取整 tensor([ 4., 10.,  5.])
四舍五入 tensor([ 4., 10.,  4.])
只取整数部分 tensor([3., 9., 4.])
只取小数部分 tensor([0.5000, 0.9820, 0.2150])
取余数 tensor([4, 3])


# 其他的一些操作

In [18]:
#重构
u = torch.tensor([[1,2,3],
                [4,5,6]])
print(u.shape)
print("resize",u.resize(3,2))
print("reshape",u.reshape(3,2))
print("vies",u.view(3,2))

torch.Size([2, 3])
resize tensor([[1, 2],
        [3, 4],
        [5, 6]])
reshape tensor([[1, 2],
        [3, 4],
        [5, 6]])
vies tensor([[1, 2],
        [3, 4],
        [5, 6]])


C:\Users\user\anaconda3\lib\site-packages\torch\_tensor.py:490: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [19]:
#获取一个tensor的值
v = torch.tensor([2.3])

print("获取tensor的值：item():\n",v.item())

获取tensor的值：item():
 2.299999952316284


In [20]:
#tensor排序
w = torch.tensor([2,22,35,9,11,4,18,13])

print("Tensor升序排序",torch.sort(w))
print("降序",torch.sort(w,descending=True))

Tensor升序排序 torch.return_types.sort(
values=tensor([ 2,  4,  9, 11, 13, 18, 22, 35]),
indices=tensor([0, 5, 3, 4, 7, 6, 1, 2]))
降序 torch.return_types.sort(
values=tensor([35, 22, 18, 13, 11,  9,  4,  2]),
indices=tensor([2, 1, 6, 7, 4, 3, 5, 0]))


In [21]:
#沿着指定维度返回最大k个数值及其索引值,top k方法
x = torch.tensor([2,22,35,9,11,4,18,13])
print("前四大的元素：",torch.topk(x,k=4,dim=0,largest=True,sorted=True,out=None))


前四大的元素： torch.return_types.topk(
values=tensor([35, 22, 18, 13]),
indices=tensor([2, 1, 6, 7]))


In [22]:
print("沿着维度返回第k个最小值和它的位置：",torch.kthvalue(x,5,dim=0))

沿着维度返回第k个最小值和它的位置： torch.return_types.kthvalue(
values=tensor(13),
indices=tensor(7))


In [23]:
#判断是否为nan，inf ，finite
y = torch.tensor([2,3,4])

print(torch.isnan(y))


tensor([False, False, False])


In [24]:
#检查参数是否无胸大
print(torch.isfinite(y))

tensor([True, True, True])


In [25]:
#tensor 转 numpy 和反转
z = torch.tensor([4,5,6])

print(z.numpy())

[4 5 6]


In [26]:
z2 = np.ones(6)
print(torch.from_numpy(z2))


tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [27]:
#判断GPU
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
a1 = torch.tensor([1,2,3],device=device)
a2 = torch.tensor([4,5,6],device=device)
res = a1+a2
print(res)

tensor([5, 7, 9])
